// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUzLckkRXMAX0pEXWgCs0gVIkGgzx0txI',
    appId: '1:1077249954572:web:aa2a116aa256cf68596f29',
    messagingSenderId: '1077249954572',
    projectId: 'fixer-c7cba',
    authDomain: 'fixer-c7cba.firebaseapp.com',
    storageBucket: 'fixer-c7cba.appspot.com',
    measurementId: 'G-T1J387NSSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtF8PyY_Tbo4QYLMmvNHrtPWv58CfMcPg',
    appId: '1:1077249954572:android:f8bc8f41de71e315596f29',
    messagingSenderId: '1077249954572',
    projectId: 'fixer-c7cba',
    storageBucket: 'fixer-c7cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIJdCBmry2VHNoZrlqUfY1HVA1mzaZu2Y',
    appId: '1:1077249954572:ios:6fcb7c7e0d4a1b7c596f29',
    messagingSenderId: '1077249954572',
    projectId: 'fixer-c7cba',
    storageBucket: 'fixer-c7cba.appspot.com',
    iosBundleId: 'com.example.fixer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIJdCBmry2VHNoZrlqUfY1HVA1mzaZu2Y',
    appId: '1:1077249954572:ios:6fcb7c7e0d4a1b7c596f29',
    messagingSenderId: '1077249954572',
    projectId: 'fixer-c7cba',
    storageBucket: 'fixer-c7cba.appspot.com',
    iosBundleId: 'com.example.fixer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUzLckkRXMAX0pEXWgCs0gVIkGgzx0txI',
    appId: '1:1077249954572:web:c610b91d6dc12b9d596f29',
    messagingSenderId: '1077249954572',
    projectId: 'fixer-c7cba',
    authDomain: 'fixer-c7cba.firebaseapp.com',
    storageBucket: 'fixer-c7cba.appspot.com',
    measurementId: 'G-TK71511W7N',
  );
}
